#!/usr/bin/env python3
"""
Merge plugin docker-compose fragments into docker-compose.plugins.yml.

This override file is loaded by docker compose alongside the main file.
Run this before `docker compose up` when ALPHARAVIS_ENABLE_PLUGIN_SYSTEM=true.
"""

import os
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
PLUGINS_DIR = REPO_ROOT / "plugins"
OUTPUT = REPO_ROOT / "docker-compose.plugins.yml"


def _env_bool(key: str, default: bool = False) -> bool:
    val = os.getenv(key, "").strip().lower()
    if not val:
        return default
    return val in ("1", "true", "yes", "on")


def main() -> None:
    plugin_system_enabled = _env_bool("ALPHARAVIS_ENABLE_PLUGIN_SYSTEM")

    if not plugin_system_enabled:
        print("Plugin system disabled — removing override file if present.")
        if OUTPUT.exists():
            OUTPUT.unlink()
            print(f"  Removed {OUTPUT}")
        return

    if not PLUGINS_DIR.exists():
        print(f"Plugins directory not found: {PLUGINS_DIR}")
        if OUTPUT.exists():
            OUTPUT.unlink()
        return

    merged: dict[str, dict] = {"services": {}}
    loaded_count = 0

    for plugin_dir in sorted(PLUGINS_DIR.iterdir()):
        if not plugin_dir.is_dir():
            continue
        if plugin_dir.name.startswith("_") or plugin_dir.name.startswith("."):
            continue

        manifest_path = plugin_dir / "plugin.yaml"
        if not manifest_path.exists():
            continue

        with open(manifest_path) as f:
            manifest = yaml.safe_load(f)

        if not manifest or not isinstance(manifest, dict):
            continue

        # Check .pluginenv for ENABLED=true
        pluginenv = plugin_dir / ".pluginenv"
        plugin_enabled = False
        if pluginenv.exists():
            try:
                for line in pluginenv.read_text().splitlines():
                    line = line.strip()
                    if line.startswith("#") or "=" not in line:
                        continue
                    key, _, val = line.partition("=")
                    if key.strip().upper() == "ENABLED":
                        plugin_enabled = val.strip().lower() in ("true", "1", "yes", "on")
                        break
            except Exception:
                pass
        if not plugin_enabled:
            print(f"  Skipping disabled plugin: {manifest.get('name', plugin_dir.name)}")
            continue

        compose = manifest.get("docker_compose", {})
        services = compose.get("services", {})

        if not services:
            continue

        for svc_name, svc_def in services.items():
            if svc_name not in merged["services"]:
                merged["services"][svc_name] = svc_def
                loaded_count += 1
                print(f"  + {svc_name} (from {manifest.get('name', plugin_dir.name)})")

    if merged["services"]:
        with open(OUTPUT, "w") as f:
            f.write(
                "# Auto-generated by scripts/merge_plugin_compose.py\n"
                "# Do not edit manually — regenerated on next run.\n"
                "# Generated from plugins/ manifests.\n"
            )
            yaml.dump(merged, f, default_flow_style=False)
        print(f"\nWrote {loaded_count} plugin service(s) to {OUTPUT}")
        print(f"Use: docker compose -f docker-compose.yml -f docker-compose.plugins.yml up")
    else:
        print("No plugin services with docker_compose definitions found.")
        if OUTPUT.exists():
            OUTPUT.unlink()
            print(f"  Removed stale {OUTPUT}")


if __name__ == "__main__":
    main()
